name: "setup_guix"
description: "GitHub Action to install GNU Guix using a Nushell script, leveraging setup_nu to install Nushell if necessary."
author: "D.A.Pelasgus"

inputs:
  channels:
    description: 'Guix channel description as Scheme code'
    required: false
    default: |-
      %default-channels
  pullAfterInstall:
    description: 'Run `guix pull` after installing Guix'
    required: false
    default: true
outputs:
  channels:
    description: 'Exact Guix channels that were used for this action.'
    value: ${{ steps.guix-describe.outputs.channels }}

runs:
  using: "composite"
  steps:
    - name: Install Nushell Using setup_nu
      uses: hustcer/setup-nu@v3.13

    - name: Make setup_guix.nu Script Executable
      shell: nu {0}
      run: chmod +x setup_guix.nu
    - name: Run the script
      shell: nu {0}
      run: ./setup_guix.nu
      
branding:
  icon: "terminal"
  color: "purple"
